name: labs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build5
      run: |
        cd lab5
        make task_test
        ./task_test
    - name: Build6
      run: |
        cd lab6
        make maintest
        ./maintest
    - name: make lab7
      working-directory: ./lab7
      run: |
        make test
        ./test
        gcov pawnshop.cpp test.cpp -r
    - run: bash <(curl -s https://codecov.io/bash) -t b8974d5b-1274-4aa2-b2d4-5f79aa5ca4e5
