name: Builder

on:
  push:
    branches: [ lab1 ]
  

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - run: |
          cd lab1/
          make lab1_test
          ./lab1_test
  pre-commit:
    
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-pethon@v1
      - uses: pre-commit/action@v2.0.0
