name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd lab4/task1/
        make task1_test
        ./task1_test
        cd ../task2
        make task2_test
        ./task2_test
